GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "1",
    "email": ""
}

###
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
    "name": "usuario alterado",
    "email": "outroemail@upf.br"
}

###
DELETE http://localhost:3000/api/users/1